export const fareChart = [
    {   
        "id_ride": "1bk",
        "key": "bk1",
        "type":"bike",
        "fare": 65,
        "passenger":1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {   
        "id_ride": "2bk",
        "key": "bk1",
        "type":"bike",
        "fare": 65,
        "passenger": 1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {   "id_ride": "3bk",
        "key": "bk1",
        "type":"bike",
        "fare": 65,
        "passenger":1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {
        "id_ride": "1cr",
        "key": "cr3",
        "type": "car",
        "fare": 90,
        "passenger":4,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {
        "id_ride": "2cr",
        "key": "cr3",
        "type": "car",
        "fare": 90,
        "passenger": 4,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {
        "id_ride": "3cr",
        "key": "cr3",
        "type": "car",
        "fare": 90,
        "passenger":4 ,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {   "id_ride": "1bs",
        "key": "bs2",
        "type": "bus",
        "fare": 20,
        "passenger":25,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "2bs",
        "key": "bs2",
        "type": "bus",
        "fare": 20 ,
        "passenger": 25,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "3bs",
        "key": "bs2",
        "type": "bus",
        "fare": 20 ,
        "passenger": 25,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "1tn",
        "key": "tn4",
        "type":"train",
        "fare": 10,
        "passenger":50,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    },
    {
        "id_ride": "2tn",
        "key": "tn4",
        "type":"train",
        "fare": 10,
        "passenger":50,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    },
    {   
        "id_ride": "3tn",
        "key": "tn4",
        "type":"train",
        "fare": 10,
        "passenger":50,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    }
    
]